### PR TITLE
remove annoying accelerate warning

### PR DESCRIPTION
**Pull request by dan-garvey**
disables usage of low_cpu_mem_usage=True in from_pretrained() calls. Can be re-enabled by using flag --low_cpu_mem_usage defaults to False to avoid spam as we don't include accelerate in our requirements.txt

### CODE REVIEW

**Comment by dan-garvey** [comment]
can restart checks after rebase once https://github.com/nod-ai/SHARK/pull/1053 is merged (will enable tests to pass)

**Comment by powderluv** [comment]
Can't thank you enough for this

**Review by powderluv — DISMISSED** [review]

**Comment by cstueckrath** [comment]
this doesn't seem to work from a git checkout at least:
Img2Img example:
```
File "\SHARK\apps\stable_diffusion\scripts\img2img.py", line 126, in img2img_inf
    img2img_obj = Image2ImagePipeline.from_pretrained(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StableDiffusionPipeline.from_pretrained() missing 1 required positional argument: 'low_cpu_mem_usage'
```

**Comment by dan-garvey** [comment]
> this doesn't seem to work from a git checkout at least: Img2Img example:
> 
> ```
> File "\SHARK\apps\stable_diffusion\scripts\img2img.py", line 126, in img2img_inf
>     img2img_obj = Image2ImagePipeline.from_pretrained(
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: StableDiffusionPipeline.from_pretrained() missing 1 required positional argument: 'low_cpu_mem_usage'
> ```
> 
> If I add that argument to the object it fails in the model wrapper. Full stack trace:
> 
> ```
> Compiling all the models with the fetched base model configuration.
> Traceback (most recent call last):
>   File "J:\sd\SHARK\shark.venv\Lib\site-packages\gradio\routes.py", line 374, in run_predict
>     output = await app.get_blocks().process_api(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "J:\sd\SHARK\shark.venv\Lib\site-packages\gradio\blocks.py", line 1017, in process_api
>     result = await self.call_function(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "J:\sd\SHARK\shark.venv\Lib\site-packages\gradio\blocks.py", line 835, in call_function
>     prediction = await anyio.to_thread.run_sync(
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "J:\sd\SHARK\shark.venv\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "J:\sd\SHARK\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread        
>     return await future
>            ^^^^^^^^^^^^
>   File "J:\sd\SHARK\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>              ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "J:\sd\SHARK\apps\stable_diffusion\scripts\img2img.py", line 126, in img2img_inf
>     img2img_obj = Image2ImagePipeline.from_pretrained(
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "J:\sd\SHARK\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 221, in from_pretrained
>     clip, unet, vae, vae_encode = mlir_import()
>                                   ^^^^^^^^^^^^^
>   File "J:\sd\SHARK\apps\stable_diffusion\src\models\model_wrappers.py", line 359, in __call__
>     return self.compile_all(base_model_fetched, need_vae_encode)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "J:\sd\SHARK\apps\stable_diffusion\src\models\model_wrappers.py", line 312, in compile_all
>     compiled_unet = self.get_unet()
>                     ^^^^^^^^^^^^^^^
>   File "J:\sd\SHARK\apps\stable_diffusion\src\models\model_wrappers.py", line 244, in get_unet
>     unet = UnetModel()
>            ^^^^^^^^^^^
>   File "J:\sd\SHARK\apps\stable_diffusion\src\models\model_wrappers.py", line 225, in __init__
>     low_cpu_mem_usage=self.low_cpu_mem_usage,
>                       ^^^^^^^^^^^^^^^^^^^^^^
>   File "J:\sd\SHARK\shark.venv\Lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
>     raise AttributeError("'{}' object has no attribute '{}'".format(
> AttributeError: 'UnetModel' object has no attribute 'low_cpu_mem_usage'
> ```

Thanks, not sure how I didnt hit this running txt2img!

**Comment by cstueckrath** [comment]
it's the same error with txt2img.

**Comment by dan-garvey** [comment]
> it's the same error with txt2img.

Can you see if the latest changes fix it for you? it works on my machine

**Comment by cstueckrath** [comment]
I'll PR into my fork

**Comment by cstueckrath** [comment]
merged it, does not work. The fork is clean except some work on setup_venv.ps1

```
To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon RX 6800 XT. Using target triple rdna2-unknown-windows.
Tuned models are currently not supported for this setting.
J:\sd\SHARK\shark.venv\Lib\site-packages\torch\jit\_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
No vmfb found. Compiling and saving to J:\sd\SHARK\apps\stable_diffusion\web\euler_scale_model_input_1_768_512fp16.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in J:\sd\SHARK\apps\stable_diffusion\web\euler_scale_model_input_1_768_512fp16.vmfb.
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_DEBUG does not conform to naming standard (Policy #LLP_LAYER_3)
No vmfb found. Compiling and saving to J:\sd\SHARK\apps\stable_diffusion\web\euler_step_1_768_512fp16.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in J:\sd\SHARK\apps\stable_diffusion\web\euler_step_1_768_512fp16.vmfb.
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_DEBUG does not conform to naming standard (Policy #LLP_LAYER_3)
Traceback (most recent call last):
  File "J:\sd\SHARK\shark.venv\Lib\site-packages\gradio\routes.py", line 374, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\sd\SHARK\shark.venv\Lib\site-packages\gradio\blocks.py", line 1017, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\sd\SHARK\shark.venv\Lib\site-packages\gradio\blocks.py", line 835, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\sd\SHARK\shark.venv\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\sd\SHARK\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread        
    return await future
           ^^^^^^^^^^^^
  File "J:\sd\SHARK\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\sd\SHARK\apps\stable_diffusion\scripts\txt2img.py", line 116, in txt2img_inf
    txt2img_obj = Text2ImagePipeline.from_pretrained(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StableDiffusionPipeline.from_pretrained() missing 1 required positional argument: 'low_cpu_mem_usage'
```

**Review by cstueckrath — APPROVED** [review]
just wanted to add that everything I've tried works with the latest changes ;)

**Review by monorimet — APPROVED** [review]
LGTM

**Pull request merged**
