### PR TITLE
add KDPM2Discrete and a force flag for setup_venv

### PR DESCRIPTION
**Pull request by cstueckrath**
like #1036 
new scheduler (doubling of its is expected)
--force flag for setup_venv.ps1 that removes and recreates venv

### CODE REVIEW

**Comment by cstueckrath** [comment]
wait, why didn't it only update the commit?
I'll have to do this from home with vscode.

**Comment by cstueckrath** [comment]
argh, I hate the Github front end
I won't touch it anymore

**Comment by cstueckrath** [comment]
feel free to close this and integrate the changes yourself
I've added some metadata for the setup_venv and a check for 3.11
You might want to have a look at this

**Comment by Shukla-Gaurav** [comment]
> argh, I hate the Github front end I won't touch it anymore

This PR is good to go, we can always squash and merge the PR from github UI itself(Where we do rebase and merge).

**Comment by Shukla-Gaurav** [comment]
> feel free to close this and integrate the changes yourself I've added some metadata for the setup_venv and a check for 3.11 You might want to have a look at this
There is no need to close this.
@powderluv can take a look into setup changes and then we can squash and merge it. Thanks!

**Pull request merged**
