### PR TITLE
Serialize torch-mlir CAPI module as bytecode instead of string.

### PR DESCRIPTION
**Pull request by monorimet**

### CODE REVIEW

**Review by pashu123 — APPROVED** [review]
LGTM!

**Review by gpetters94 — DISMISSED** [review]
LGTM

**Comment by pashu123** [comment]
I think https://github.com/nod-ai/SHARK/blob/e9e61c789f367130d202ecf7ad272bc59729c5fe/shark/shark_downloader.py#L139 reading of files should also be changed. We will be uploading the bytecode file to tank and while downloading it should be reading the bytecode file rather than str files.

**Comment by pashu123** [comment]
Also, all the string notation of mlir_module should be changed to actual module. https://github.com/nod-ai/SHARK/blob/01fdf5ee16ea91de91c7a503fb2cfc2ef56e6d4b/shark/shark_inference.py#L66

**Comment by monorimet** [comment]
> Also, all the string notation of mlir_module should be changed to actual module.
> 
> https://github.com/nod-ai/SHARK/blob/01fdf5ee16ea91de91c7a503fb2cfc2ef56e6d4b/shark/shark_inference.py#L66

Thanks for the suggestions!!

**Comment by monorimet** [comment]
@pashu123 had some issues reading in the bytecode from torch-mlir -- When reading it through SharkDownloader with `mode=rb` IREE-compile fails with `<stdin>:1:2: error: unexpected character` where the line referenced is something along the lines of `b'#map0 = affine_map<(d0, d1) -> (0, d1)>\n`

the TF and TFlite .mlir seem to work with either mode.

I'll keep working on this when I have a bit of downtime -- I think I need to make sure the code I referenced from Ramiro's change in IREE is implemented correctly for our use case (maybe writing the result of `bytecode_stream.getvalue()` to a file is different from passing it as an argument?)

**Review by pashu123 — DISMISSED** [review]

**Review by pashu123 — APPROVED** [review]

**Pull request merged**
