### PR TITLE
Add --local_tank_cache flag and update requirements.

### PR DESCRIPTION
**Pull request by monorimet**

### CODE REVIEW

**Comment by pashu123** [comment]
LGTM!

**Review by pashu123 — APPROVED** [review]
LGTM!

**Comment by pashu123** [comment]
@monorimet I think there are conflicts.

**Comment by monorimet** [comment]
> @monorimet I think there are conflicts.

I should have solved all the merge conflicts, unless you saw some while reviewing that git didn't catch

**Pull request merged**
