### PR TITLE
Fix low vram mode issues

### PR DESCRIPTION
**Pull request by jinchen62**
- add ondemand back to img2img
- workaround memory leak for batch count

### CODE REVIEW

**Review by monorimet — APPROVED** [review]

**Comment by quasaray** [comment]
These changes seem to have broken outpainting, the config was not updated with `ondemand`

**Comment by jinchen62** [comment]
@quasaray Hi, outpainting doesn't have the support of ondemand yet.

**Comment by quasaray** [comment]
@jinchen62 I encountered a runtime error with the latest prerelease, this PR expects the `ondemand` parameter in utils.Config to be set, but the reference to utils.Config in outpainting was not updated to set this when it is created. 
This has nothing to do with actually using ondemand

**Comment by jinchen62** [comment]
@quasaray Do you encounter this on other modes like img2img?

**Comment by quasaray** [comment]
I have only used text2img and outpainting so far, I only encountered the error on outpainting

**Comment by jinchen62** [comment]
@quasaray thanks for pointing it out, I have push up a PR

**Pull request merged**
