### PR TITLE
Use turbine for gen_sharktank imports.

### PR DESCRIPTION
**Pull request by monorimet**
Needs these changes https://github.com/nod-ai/SHARK-Turbine/pull/102 for a successful run for certain models.

TODO: turbine integration for models that accept multiple inputs.
TODO: complete sets of artifacts for turbine path (needs hash generating for each .mlir)

### CODE REVIEW

**Comment by dan-garvey** [comment]
vk failure seems gen related

**Comment by monorimet** [comment]
> vk failure seems gen related

yep, needed to set the jobs to use IMPORTER=1 as that's where shark-turbine is added to requirements

**Comment by dan-garvey** [comment]
fyi https://github.com/nod-ai/SHARK-Turbine/pull/176

**Comment by monorimet** [comment]
Closing as model testing/validation will live in SHARK-Turbine
fyi @dan-garvey

**Pull request closed without merging**
