### PR TITLE
Add v-diffusion model

### PR DESCRIPTION
**Pull request by vivekkhandelwal1**

### CODE REVIEW

**Comment by pashu123** [comment]
Please format .py files with `black --line-length 79  .  `.

**Review by pashu123 — APPROVED** [review]
LGTM! We can merge after the pytorch and torch-mlir changes.

**Comment by vivekkhandelwal1** [comment]
> Please format .py files with `black --line-length 79 . `.

Done.

**Comment by powderluv** [comment]
ideally if you can pull in the pytorch decomp into this sample.  Ok to merge and do it in a follow on .

**Pull request merged**
