### PR TITLE
move beta to release

### PR DESCRIPTION
**Pull request by dan-garvey**

### CODE REVIEW

**Review by powderluv — COMMENTED** [review]
Lets land right after @Shukla-Gaurav re-org patch.

**Comment by dan-garvey** [comment]
https://github.com/nod-ai/SHARK/actions/runs/4058600035 manual ci for this patch (didnt trigger)

**Review by monorimet — APPROVED** [review]

**Comment by powderluv** [comment]
don't think this is taking effect in the next txt2img and web path

**Comment by powderluv** [comment]
I pulled these changes and ran @Shukla-Gaurav new web ui in apps/ and it shows

```
Using cached models from C:\Users\anush\.local/shark_tank/...
100%|█████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 5.84kB/s]
100%|█████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 10.2kB/s]
No vmfb found. Compiling and saving to C:\g\shark\apps\stable_diffusion\web\clip_19dec_v2p1base_fp32_64_vulkan-00000000-6300-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna3-7900-windows from command line args
```

**Comment by dan-garvey** [comment]
> I pulled these changes and ran @Shukla-Gaurav new web ui in apps/ and it shows
> 
> ```
> Using cached models from C:\Users\anush\.local/shark_tank/...
> 100%|█████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 5.84kB/s]
> 100%|█████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 10.2kB/s]
> No vmfb found. Compiling and saving to C:\g\shark\apps\stable_diffusion\web\clip_19dec_v2p1base_fp32_64_vulkan-00000000-6300-0000-0000-000000000000.vmfb
> Using target triple -iree-vulkan-target-triple=rdna3-7900-windows from command line args
> ```

can you try fp16

**Comment by powderluv** [comment]
that was for fp16. it just downloads fp32 for clip

**Comment by dan-garvey** [comment]
I see, he made a new models_db.json file, patch coming

**Pull request merged**
