### PR TITLE
Force TensorFlow to use CPU when generating model and golden values.

### PR DESCRIPTION
**Pull request by monorimet**
xfails will be updated once issues are filed for remaining failures.

### CODE REVIEW

**Comment by pashu123** [comment]
@monorimet You can also add the tf part in shark_importer as well.

**Comment by monorimet** [comment]
> @monorimet You can also add the tf part in shark_importer as well.

I put it in tank/masked_lm_tf.py so that it would work for benchmarks as well. Should it go in importer as well?

**Comment by pashu123** [comment]
> > @monorimet You can also add the tf part in shark_importer as well.
> 
> I put it in tank/masked_lm_tf.py so that it would work for benchmarks as well. Should it go in importer as well?

Oh! It's fine over there.

**Review by AmosLewis — APPROVED** [review]
LGTM

**Pull request merged**
