### PR TITLE
Increase JPEG output quality & disable subsampling

### PR DESCRIPTION
**Pull request by xzuyn**
Increased to JPEG95 from the default JPEG75 which is way too compressed. Output image size is now ~100-200kb. Previously was ~20kb.

### CODE REVIEW

**Review by powderluv — COMMENTED** [review]
Awesome. Do we need it for the cli too ?

**Comment by xzuyn** [comment]
I've only really used the GUI so I'm not sure. I think that should add the change for cli.

**Review by powderluv — APPROVED** [review]

**Comment by powderluv** [comment]
Please run black --line-length 79 .

You can install with pip install black.

**Comment by xzuyn** [comment]
what for?

**Comment by powderluv** [comment]
Oh the CI has a bunch of python code formatting checks. See the build failure in the CI.

**Comment by xzuyn** [comment]
fixed the line length formatting.

**Review by powderluv — APPROVED** [review]
We can merge this -- but don't we just want 100%

**Comment by xzuyn** [comment]
Documentation says going above 95 isn't recommended.

> The image quality, on a scale from 0 (worst) to 95 (best), or the string keep. The default is 75. Values above 95 should be avoided; 100 disables portions of the JPEG compression algorithm, and results in large files with hardly any gain in image quality. The value keep is only valid for JPEG files and will retain the original image quality level, subsampling, and qtables.

Maybe a toggle between PNG and JPEG95 at some point?

**Comment by powderluv** [comment]
yup reasonable to add png

**Pull request merged**
