### PR TITLE
Remove tensorflow package dep for tflite sharkdownloader tests

### PR DESCRIPTION
**Pull request by AmosLewis**

### CODE REVIEW

**Review by monorimet — APPROVED** [review]
LGTM!

**Review by pashu123 — DISMISSED** [review]
LGTM!

**Comment by pashu123** [comment]
1 failed and 2 xpassed. Please update the tests.

**Comment by AmosLewis** [comment]
> 1 failed and 2 xpassed. Please update the tests.

Done

**Review by monorimet — APPROVED** [review]
LGTM

**Pull request merged**
