### PR TITLE
Pass --iree-hal-cuda-llvm-target-arch for GPU execution automatically.

### PR DESCRIPTION
**Pull request by monorimet**
Also adds in IREE DeviceArray support for Tensorflow frontend.

### CODE REVIEW

**Comment by powderluv** [comment]
Commit message needs to be updated

**Review by powderluv — COMMENTED** [review]
Let's set the flag only if sm 70 or above

**Comment by pashu123** [comment]
I have updated the shark_trainer. PTAL.

**Comment by pashu123** [comment]
Also, @monorimet If you can modify this example: https://github.com/nod-ai/SHARK/blob/main/shark/examples/shark_training/bert_training_tf.py That would be great.

**Pull request merged**
