### PR TITLE
add folders based on current date to generated_imgs

### PR DESCRIPTION
**Pull request by cstueckrath**
so it's \generated_imgs\20230215\\*.*

bakes a new csv, too

### CODE REVIEW

**Comment by PhaneeshB** [comment]
Hi @cstueckrath! Thanks for your contribution

looks like there's a lint failure
- you can check the failures using `black --line-length 79 --check --diff .`
- to fix them just use `black --line-length 79  .` (NOTE : this would format any other python files you may have in cwd)

**Comment by cstueckrath** [comment]
fixed the line length issue

**Comment by Shukla-Gaurav** [comment]
@cstueckrath Thanks for the change. You need to rebase this PR, also now you need to change at only one location instead of many -> apps/stable_diffusion/src/utils/utils.py

**Comment by cstueckrath** [comment]
sure thing. I'll close this then?
Would I revert and rebase if not?

**Comment by Shukla-Gaurav** [comment]
@cstueckrath yes, we can close this now. https://github.com/nod-ai/SHARK/pull/1027 addresses this.

**Pull request closed without merging**
