### PR TITLE
(SD) Fix tokenizers imports in pyinstaller builds.

### PR DESCRIPTION
**Pull request by monorimet**
Also disables vae tuning for RDNA3.

### CODE REVIEW

**Review by gpetters94 — COMMENTED** [review]
LGTM

**Review by dan-garvey — COMMENTED** [review]
why does it not matter that we get rid of gcs and opencv?

**Comment by monorimet** [comment]
> why does it not matter that we get rid of gcs and opencv?

see https://github.com/nod-ai/SHARK/actions/runs/6142135995/job/16663459666#step:6:1042

```
2498 WARNING: collect_data_files - skipping data collection for module 'opencv_python' as it is not a package.
2737 WARNING: collect_data_files - skipping data collection for module 'google_cloud_storage' as it is not a package.
```

meaning we can remove them as they've always been skipped

**Comment by PhaneeshB** [comment]
> meaning we can remove them as they've always been skipped (at least the shark_downloader doesn't seem to need gcs. I'm not sure about opencv but hasn't posed issues yet.)


Not sure why exe is skipping opencv, iirc,
OpenCV is imported for one of the stencil modes

**Review by PhaneeshB — APPROVED** [review]
LGTM!

**Pull request merged**
