### PR TITLE
[WEB] Iterative Output for Demo

### PR DESCRIPTION
**Pull request by cpietsch**
Wouldn't it be cool to see the progress image while running diffusion ?

Added support for [Gradio's Iterative Output](https://gradio.app/key_features/#iterative-outputs) to the web demo.
This might be even nicer than having a progressbar #601, though we could also add a seperate progressbar mis-using a [label](https://gradio.app/docs/#label) or waiting for [tqdm integration](https://github.com/gradio-app/gradio/issues/340).

Update currently set to every 20 step ``iterative_output_step = 20``

gradio

### CODE REVIEW

**Comment by powderluv** [comment]
Thank you for the contribution. We used to have the "live preview" option before and we dropped it. If there is interest in having it we can add it and merge this change. But I think we should have it as a radio button turned off by default.

**Comment by cpietsch** [comment]
will add the radio button

**Comment by cpietsch** [comment]
added a dropdown
image

**Comment by powderluv** [comment]
Do you forsee any other option in the drop down ? If not best to have it as a radio button. It should be there in prior git history and the `rdna` branch probably has it

**Comment by powderluv** [comment]
btw if you view it in dark mode the UI looks a little better (or set your windows theme to dark). We need to fix that.

**Comment by cpietsch** [comment]
I added the dropdown, because you can choose the steps instead of a fixed value
``choices=["None", "5", "10", "20"],``
https://github.com/cpietsch/SHARK/blob/patch-2/web/index.py#L115

**Comment by powderluv** [comment]
Thanks for the PR. Just a heads up we plan to move the UI into the main stable Diffusion script so expect some churn but then you can interchangeably just cli and webui.

**Comment by powderluv** [comment]
Please fix the CI lint failures. Just need to run black

**Comment by cpietsch** [comment]
fixed lint failures
great to see moving the web stuff into the main script - first I was confused seeing 2 times the diffusion script in the repo

**Comment by powderluv** [comment]
finally the merge of the scripts happened. Lets close this and open a a new one if required.

**Pull request closed without merging**
