### PR TITLE
Update model annotation tool

### PR DESCRIPTION
**Pull request by yzhang93**
Usage:
from shark.model_annotation import model_annotation
with create_context() as ctx:
  module = model_annotation(ctx, input_contents=..., config_path=..., search_op=...)

Example:
The example is to annotate the minilm model with GPU config file. 
python model_annotation.py /nodclouddata/vivian/minilm_model/model.mlir /nodclouddata/vivian/minilm_model/model_config.json

### CODE REVIEW

**Review by powderluv — APPROVED** [review]
Please also add a readme

**Comment by yzhang93** [comment]
> Please also add a readme

@powderluv Actually there's not much to write in a separate README file. It's just a function call to model_annotation(). I'll let @monorimet to decide where to store the tuned config files and where to call this function. I can provide the config files for tank models.

**Comment by monorimet** [comment]
Looks good. I'll spend some time with this so I'm familiar enough to integrate.

1. You can `pip install black` and run `black --line-length 79 . ` from SHARK base directory for the formatting issues.

**Review by monorimet — DISMISSED** [review]

**Comment by yzhang93** [comment]
@monorimet Thanks! I've updated the format. Could you take a look again?

**Pull request merged**
